fix: overwrite w3c button up/down command on mobiles
gemini-testing/hermione-wdio-migrator pull request #23
Opened 2023-06-26 13:00 UTC by shadowusr

### Подробности

- в [hermione-wdio-migrator](https://github.com/gemini-testing/hermione-wdio-migrator/blob/b784cd767fb6255057afe79c87bf1e2ede05e12e/lib/commands/protocol/buttonDown.js#L7) перед добавлением команды сначала выполняется проверка, не существует ли такая команда, а если существует — то патч не применяется
- в [webdriver](https://github.com/webdriverio/webdriverio/blob/7b8319ff91f331683bb613012aa3ffc10824d8df/packages/webdriver/src/utils.ts#L180) исключительно для мобильных браузеров даже в протокле webdriver на инстансе браузера задаются методы и webdriver, и jsonwire, даже если браузер на самом деле не поддерживает такие команды
- это приводит к тому, что wdio-migrator не применяет патч, команда остается jsonwire, который падает из-за отсутствия поддержки со стороны браузера

### Что сделано?

- Исправлена проблема cannot call non-W3C command in W3C mode в современных версиях chrome-phone

### Принятые решения

- Перезаписывать команды `buttonUp` и `buttonDown`, даже если они уже есть в браузере, если находимся в режиме W3C

### Как я тестировал?

Запускал пропатченную версию на проекте с тестами, которые ранее падали

2023-06-26 13:04 UTC, KuznetsovRoman requested changes
Тестов не хватает

2023-06-26 15:09 UTC, DudaGod approved these changes
/ok (только тест нужно докинуть)

2023-06-28 10:57 UTC, DudaGod approved these changes
/ok_2

2023-06-28 10:57 UTC, DudaGod commented on lib/commands/mobile/swipe.js
> +            const moveDuration = Math.hypot(xOffset, yOffset) / speed * 1000;
👍

2023-06-28 22:22 UTC, merged